/**
 * The Giant Swarm API
 * This is the documentation for the Giant Swarm API.  For an introduction to Giant Swarm, refer to the [documentation site](https://docs.giantswarm.io/).  The Giant Swarm API attempts to behave in a __restful__ way. As a developer, you access resources using the `GET` method and, for example, delete them using the same path and the `DELETE` method.  Accessing resources via GET usually returns all information available about a resource, while collections, like for example the list of all clusters you have access to, only contain a selected few attributes of each member item.  Some requests, like for example the request to create a new cluster, don't return the resource itself. Instead, the response delivers a standard message body, showing a `code` and a `message` part. The `message` contains information for you or a client's end user. The `code` attribute contains some string (example: `RESOURCE_CREATED`) that is supposed to give you details on the state of the operation, in addition to standard HTTP status codes. This message format is also used in the case of errors. We provide a [list of all response codes](https://github.com/giantswarm/api-spec/blob/master/details/RESPONSE_CODES.md) outside this documentation.  Feedback on the API as well as this documentation is welcome via `support@giantswarm.io` or on IRC channel [#giantswarm](irc://irc.freenode.org:6667/#giantswarm) on freenode.  ## Source  The source of this documentation is available on [GitHub](https://github.com/giantswarm/api-spec). 
 *
 * The version of the OpenAPI document: 4.0.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.1.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineObject', 'model/V4AddCredentialsRequest', 'model/V4GenericResponse', 'model/V4GetCredentialResponse', 'model/V4Organization', 'model/V4OrganizationListItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/InlineObject'), require('../model/V4AddCredentialsRequest'), require('../model/V4GenericResponse'), require('../model/V4GetCredentialResponse'), require('../model/V4Organization'), require('../model/V4OrganizationListItem'));
  } else {
    // Browser globals (root is window)
    if (!root.GiantSwarm) {
      root.GiantSwarm = {};
    }
    root.GiantSwarm.OrganizationsApi = factory(root.GiantSwarm.ApiClient, root.GiantSwarm.InlineObject, root.GiantSwarm.V4AddCredentialsRequest, root.GiantSwarm.V4GenericResponse, root.GiantSwarm.V4GetCredentialResponse, root.GiantSwarm.V4Organization, root.GiantSwarm.V4OrganizationListItem);
  }
}(this, function(ApiClient, InlineObject, V4AddCredentialsRequest, V4GenericResponse, V4GetCredentialResponse, V4Organization, V4OrganizationListItem) {
  'use strict';

  /**
   * Organizations service.
   * @module api/OrganizationsApi
   * @version 4.0.0
   */

  /**
   * Constructs a new OrganizationsApi. 
   * @alias module:api/OrganizationsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Set credentials
     * Add a set of credentials to the organization allowing the creation and operation of clusters within a cloud provider account/subscription.  The actual type of these credentials depends on the cloud provider the installation is running on. AWS and Azure are currently supported.  Credentials in an organization are immutable. Each organization can only have one set of credentials.  Once credentials have been set for an organization, they are used for every new cluster that will be created for the organization.  ### Example request body for AWS  ```json {   \"provider\": \"aws\",   \"aws\": {     \"roles\": {       \"admin\": \"arn:aws:iam::123456789012:role/GiantSwarmAdmin\",       \"awsoperator\": \"arn:aws:iam::123456789012:role/GiantSwarmAWSOperator\"     }   } } ```  ### Example request body for Azure  ```json {   \"provider\": \"azure\",   \"azure\": {     \"credential\": {       \"client_id\": \"c93bf55e-5bf7-4966-ad2b-e6f6e7721d50\",       \"secret_key\": \"720e38f7-3af4-463c-9313-abcdf2ead612\",       \"subscription_id\": \"b388b7c7-4479-4040-9ac5-1e13edd6b1cd\",       \"tenant_id\": \"3dd2e94a-92ba-434c-99be-32bb65864a99\"     }   } } ``` 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {String} organizationId An ID for the organization. This ID must be unique and match this regular expression: ^[a-z0-9_]{4,30}$ 
     * @param {module:model/V4AddCredentialsRequest} v4AddCredentialsRequest 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/V4GenericResponse} and HTTP response
     */
    this.addCredentialsWithHttpInfo = function(authorization, organizationId, v4AddCredentialsRequest, opts) {
      opts = opts || {};
      var postBody = v4AddCredentialsRequest;
      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling addCredentials");
      }
      // verify the required parameter 'organizationId' is set
      if (organizationId === undefined || organizationId === null) {
        throw new Error("Missing the required parameter 'organizationId' when calling addCredentials");
      }
      // verify the required parameter 'v4AddCredentialsRequest' is set
      if (v4AddCredentialsRequest === undefined || v4AddCredentialsRequest === null) {
        throw new Error("Missing the required parameter 'v4AddCredentialsRequest' when calling addCredentials");
      }

      var pathParams = {
        'organization_id': organizationId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization,
        'X-Request-ID': opts['xRequestID'],
        'X-Giant-Swarm-Activity': opts['xGiantSwarmActivity'],
        'X-Giant-Swarm-CmdLine': opts['xGiantSwarmCmdLine']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = V4GenericResponse;
      return this.apiClient.callApi(
        '/v4/organizations/{organization_id}/credentials/', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Set credentials
     * Add a set of credentials to the organization allowing the creation and operation of clusters within a cloud provider account/subscription.  The actual type of these credentials depends on the cloud provider the installation is running on. AWS and Azure are currently supported.  Credentials in an organization are immutable. Each organization can only have one set of credentials.  Once credentials have been set for an organization, they are used for every new cluster that will be created for the organization.  ### Example request body for AWS  ```json {   \"provider\": \"aws\",   \"aws\": {     \"roles\": {       \"admin\": \"arn:aws:iam::123456789012:role/GiantSwarmAdmin\",       \"awsoperator\": \"arn:aws:iam::123456789012:role/GiantSwarmAWSOperator\"     }   } } ```  ### Example request body for Azure  ```json {   \"provider\": \"azure\",   \"azure\": {     \"credential\": {       \"client_id\": \"c93bf55e-5bf7-4966-ad2b-e6f6e7721d50\",       \"secret_key\": \"720e38f7-3af4-463c-9313-abcdf2ead612\",       \"subscription_id\": \"b388b7c7-4479-4040-9ac5-1e13edd6b1cd\",       \"tenant_id\": \"3dd2e94a-92ba-434c-99be-32bb65864a99\"     }   } } ``` 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {String} organizationId An ID for the organization. This ID must be unique and match this regular expression: ^[a-z0-9_]{4,30}$ 
     * @param {module:model/V4AddCredentialsRequest} v4AddCredentialsRequest 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/V4GenericResponse}
     */
    this.addCredentials = function(authorization, organizationId, v4AddCredentialsRequest, opts) {
      return this.addCredentialsWithHttpInfo(authorization, organizationId, v4AddCredentialsRequest, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create an organization
     * This operation allows a user to create an organization. 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {String} organizationId An ID for the organization. This ID must be unique and match this regular expression: ^[a-z0-9_]{4,30}$ 
     * @param {module:model/V4Organization} v4Organization 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/V4Organization} and HTTP response
     */
    this.addOrganizationWithHttpInfo = function(authorization, organizationId, v4Organization, opts) {
      opts = opts || {};
      var postBody = v4Organization;
      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling addOrganization");
      }
      // verify the required parameter 'organizationId' is set
      if (organizationId === undefined || organizationId === null) {
        throw new Error("Missing the required parameter 'organizationId' when calling addOrganization");
      }
      // verify the required parameter 'v4Organization' is set
      if (v4Organization === undefined || v4Organization === null) {
        throw new Error("Missing the required parameter 'v4Organization' when calling addOrganization");
      }

      var pathParams = {
        'organization_id': organizationId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization,
        'X-Request-ID': opts['xRequestID'],
        'X-Giant-Swarm-Activity': opts['xGiantSwarmActivity'],
        'X-Giant-Swarm-CmdLine': opts['xGiantSwarmCmdLine']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = V4Organization;
      return this.apiClient.callApi(
        '/v4/organizations/{organization_id}/', 'PUT',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create an organization
     * This operation allows a user to create an organization. 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {String} organizationId An ID for the organization. This ID must be unique and match this regular expression: ^[a-z0-9_]{4,30}$ 
     * @param {module:model/V4Organization} v4Organization 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/V4Organization}
     */
    this.addOrganization = function(authorization, organizationId, v4Organization, opts) {
      return this.addOrganizationWithHttpInfo(authorization, organizationId, v4Organization, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete an organization
     * This operation allows a user to delete an organization that they are a member of. Admin users can delete any organization. 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {String} organizationId An ID for the organization. This ID must be unique and match this regular expression: ^[a-z0-9_]{4,30}$ 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/V4GenericResponse} and HTTP response
     */
    this.deleteOrganizationWithHttpInfo = function(authorization, organizationId, opts) {
      opts = opts || {};
      var postBody = null;
      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling deleteOrganization");
      }
      // verify the required parameter 'organizationId' is set
      if (organizationId === undefined || organizationId === null) {
        throw new Error("Missing the required parameter 'organizationId' when calling deleteOrganization");
      }

      var pathParams = {
        'organization_id': organizationId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization,
        'X-Request-ID': opts['xRequestID'],
        'X-Giant-Swarm-Activity': opts['xGiantSwarmActivity'],
        'X-Giant-Swarm-CmdLine': opts['xGiantSwarmCmdLine']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = V4GenericResponse;
      return this.apiClient.callApi(
        '/v4/organizations/{organization_id}/', 'DELETE',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Delete an organization
     * This operation allows a user to delete an organization that they are a member of. Admin users can delete any organization. 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {String} organizationId An ID for the organization. This ID must be unique and match this regular expression: ^[a-z0-9_]{4,30}$ 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/V4GenericResponse}
     */
    this.deleteOrganization = function(authorization, organizationId, opts) {
      return this.deleteOrganizationWithHttpInfo(authorization, organizationId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get credential details
     * Returns details for a particular set of credentials, identified by its ID. The returned data does not contain any secrets (i. e. passphrase, secret key). For more information on credentials, see [Set credentials](#operation/addCredentials).  ### Example response body for AWS  ```json {   \"id\": \"a1b2c3\",   \"provider\": \"aws\",   \"aws\": {     \"roles\": {       \"admin\": \"arn:aws:iam::123456789012:role/GiantSwarmAdmin\",       \"awsoperator\": \"arn:aws:iam::123456789012:role/GiantSwarmAWSOperator\"     }   } } ```  ### Example response body for Azure  ```json {   \"id\": \"a1b2c3\",   \"provider\": \"azure\",   \"azure\": {     \"credential\": {       \"client_id\": \"c93bf55e-5bf7-4966-ad2b-e6f6e7721d50\",       \"subscription_id\": \"b388b7c7-4479-4040-9ac5-1e13edd6b1cd\",       \"tenant_id\": \"3dd2e94a-92ba-434c-99be-32bb65864a99\"     }   } } ``` 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {String} organizationId An ID for the organization. This ID must be unique and match this regular expression: ^[a-z0-9_]{4,30}$ 
     * @param {String} credentialId Unique ID of a credential set
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/V4GetCredentialResponse} and HTTP response
     */
    this.getCredentialWithHttpInfo = function(authorization, organizationId, credentialId, opts) {
      opts = opts || {};
      var postBody = null;
      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling getCredential");
      }
      // verify the required parameter 'organizationId' is set
      if (organizationId === undefined || organizationId === null) {
        throw new Error("Missing the required parameter 'organizationId' when calling getCredential");
      }
      // verify the required parameter 'credentialId' is set
      if (credentialId === undefined || credentialId === null) {
        throw new Error("Missing the required parameter 'credentialId' when calling getCredential");
      }

      var pathParams = {
        'organization_id': organizationId,
        'credential_id': credentialId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization,
        'X-Request-ID': opts['xRequestID'],
        'X-Giant-Swarm-Activity': opts['xGiantSwarmActivity'],
        'X-Giant-Swarm-CmdLine': opts['xGiantSwarmCmdLine']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = V4GetCredentialResponse;
      return this.apiClient.callApi(
        '/v4/organizations/{organization_id}/credentials/{credential_id}/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get credential details
     * Returns details for a particular set of credentials, identified by its ID. The returned data does not contain any secrets (i. e. passphrase, secret key). For more information on credentials, see [Set credentials](#operation/addCredentials).  ### Example response body for AWS  ```json {   \"id\": \"a1b2c3\",   \"provider\": \"aws\",   \"aws\": {     \"roles\": {       \"admin\": \"arn:aws:iam::123456789012:role/GiantSwarmAdmin\",       \"awsoperator\": \"arn:aws:iam::123456789012:role/GiantSwarmAWSOperator\"     }   } } ```  ### Example response body for Azure  ```json {   \"id\": \"a1b2c3\",   \"provider\": \"azure\",   \"azure\": {     \"credential\": {       \"client_id\": \"c93bf55e-5bf7-4966-ad2b-e6f6e7721d50\",       \"subscription_id\": \"b388b7c7-4479-4040-9ac5-1e13edd6b1cd\",       \"tenant_id\": \"3dd2e94a-92ba-434c-99be-32bb65864a99\"     }   } } ``` 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {String} organizationId An ID for the organization. This ID must be unique and match this regular expression: ^[a-z0-9_]{4,30}$ 
     * @param {String} credentialId Unique ID of a credential set
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/V4GetCredentialResponse}
     */
    this.getCredential = function(authorization, organizationId, credentialId, opts) {
      return this.getCredentialWithHttpInfo(authorization, organizationId, credentialId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get credentials
     * Returns credentials for an organization, if available. For more information on credentials, see [Set credentials](#operation/addCredentials).  Here is another paragraph.  ### Example response body for AWS  ```json [   {     \"id\": \"a1b2c3\",     \"provider\": \"aws\",     \"aws\": {       \"roles\": {         \"admin\": \"arn:aws:iam::123456789012:role/GiantSwarmAdmin\",         \"awsoperator\": \"arn:aws:iam::123456789012:role/GiantSwarmAWSOperator\"       }     }   } ] ```  ### Example response body for Azure  ```json [   {     \"id\": \"a1b2c3\",     \"provider\": \"azure\",     \"azure\": {       \"credential\": {         \"client_id\": \"c93bf55e-5bf7-4966-ad2b-e6f6e7721d50\",         \"subscription_id\": \"b388b7c7-4479-4040-9ac5-1e13edd6b1cd\",         \"tenant_id\": \"3dd2e94a-92ba-434c-99be-32bb65864a99\"       }     }   } ] ``` 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {String} organizationId An ID for the organization. This ID must be unique and match this regular expression: ^[a-z0-9_]{4,30}$ 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/V4GetCredentialResponse>} and HTTP response
     */
    this.getCredentialsWithHttpInfo = function(authorization, organizationId, opts) {
      opts = opts || {};
      var postBody = null;
      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling getCredentials");
      }
      // verify the required parameter 'organizationId' is set
      if (organizationId === undefined || organizationId === null) {
        throw new Error("Missing the required parameter 'organizationId' when calling getCredentials");
      }

      var pathParams = {
        'organization_id': organizationId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization,
        'X-Request-ID': opts['xRequestID'],
        'X-Giant-Swarm-Activity': opts['xGiantSwarmActivity'],
        'X-Giant-Swarm-CmdLine': opts['xGiantSwarmCmdLine']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [V4GetCredentialResponse];
      return this.apiClient.callApi(
        '/v4/organizations/{organization_id}/credentials/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get credentials
     * Returns credentials for an organization, if available. For more information on credentials, see [Set credentials](#operation/addCredentials).  Here is another paragraph.  ### Example response body for AWS  ```json [   {     \"id\": \"a1b2c3\",     \"provider\": \"aws\",     \"aws\": {       \"roles\": {         \"admin\": \"arn:aws:iam::123456789012:role/GiantSwarmAdmin\",         \"awsoperator\": \"arn:aws:iam::123456789012:role/GiantSwarmAWSOperator\"       }     }   } ] ```  ### Example response body for Azure  ```json [   {     \"id\": \"a1b2c3\",     \"provider\": \"azure\",     \"azure\": {       \"credential\": {         \"client_id\": \"c93bf55e-5bf7-4966-ad2b-e6f6e7721d50\",         \"subscription_id\": \"b388b7c7-4479-4040-9ac5-1e13edd6b1cd\",         \"tenant_id\": \"3dd2e94a-92ba-434c-99be-32bb65864a99\"       }     }   } ] ``` 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {String} organizationId An ID for the organization. This ID must be unique and match this regular expression: ^[a-z0-9_]{4,30}$ 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/V4GetCredentialResponse>}
     */
    this.getCredentials = function(authorization, organizationId, opts) {
      return this.getCredentialsWithHttpInfo(authorization, organizationId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get organization details
     * This operation fetches organization details. 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {String} organizationId An ID for the organization. This ID must be unique and match this regular expression: ^[a-z0-9_]{4,30}$ 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/V4Organization} and HTTP response
     */
    this.getOrganizationWithHttpInfo = function(authorization, organizationId, opts) {
      opts = opts || {};
      var postBody = null;
      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling getOrganization");
      }
      // verify the required parameter 'organizationId' is set
      if (organizationId === undefined || organizationId === null) {
        throw new Error("Missing the required parameter 'organizationId' when calling getOrganization");
      }

      var pathParams = {
        'organization_id': organizationId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization,
        'X-Request-ID': opts['xRequestID'],
        'X-Giant-Swarm-Activity': opts['xGiantSwarmActivity'],
        'X-Giant-Swarm-CmdLine': opts['xGiantSwarmCmdLine']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = V4Organization;
      return this.apiClient.callApi(
        '/v4/organizations/{organization_id}/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get organization details
     * This operation fetches organization details. 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {String} organizationId An ID for the organization. This ID must be unique and match this regular expression: ^[a-z0-9_]{4,30}$ 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/V4Organization}
     */
    this.getOrganization = function(authorization, organizationId, opts) {
      return this.getOrganizationWithHttpInfo(authorization, organizationId, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get organizations
     * This operation allows to fetch a list of organizations the user is a member of. In the case of an admin user, the result includes all existing organizations. 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/V4OrganizationListItem>} and HTTP response
     */
    this.getOrganizationsWithHttpInfo = function(authorization, opts) {
      opts = opts || {};
      var postBody = null;
      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling getOrganizations");
      }

      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization,
        'X-Request-ID': opts['xRequestID'],
        'X-Giant-Swarm-Activity': opts['xGiantSwarmActivity'],
        'X-Giant-Swarm-CmdLine': opts['xGiantSwarmCmdLine']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = [V4OrganizationListItem];
      return this.apiClient.callApi(
        '/v4/organizations/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get organizations
     * This operation allows to fetch a list of organizations the user is a member of. In the case of an admin user, the result includes all existing organizations. 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/V4OrganizationListItem>}
     */
    this.getOrganizations = function(authorization, opts) {
      return this.getOrganizationsWithHttpInfo(authorization, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Modify organization
     * This operation allows you to modify an existing organization. You must be a member of the organization or an admin in order to use this endpoint.  The following attributes can be modified:  - `members`: By modifying the array of members, members can be added to or removed from the organization  The request body must conform with the [JSON Patch Merge (RFC 7386)](https://tools.ietf.org/html/rfc7386) standard. Requests have to be sent with the `Content-Type: application/merge-patch+json` header.  The full request must be valid before it will be executed, currently this means every member you attempt to add to the organization must actually exist in the system. If any member you attempt to add is invalid, the entire patch operation will fail, no members will be added or removed, and an error message will explain which members in your request are invalid. 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {String} organizationId An ID for the organization. This ID must be unique and match this regular expression: ^[a-z0-9_]{4,30}$ 
     * @param {module:model/InlineObject} inlineObject 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/V4Organization} and HTTP response
     */
    this.modifyOrganizationWithHttpInfo = function(authorization, organizationId, inlineObject, opts) {
      opts = opts || {};
      var postBody = inlineObject;
      // verify the required parameter 'authorization' is set
      if (authorization === undefined || authorization === null) {
        throw new Error("Missing the required parameter 'authorization' when calling modifyOrganization");
      }
      // verify the required parameter 'organizationId' is set
      if (organizationId === undefined || organizationId === null) {
        throw new Error("Missing the required parameter 'organizationId' when calling modifyOrganization");
      }
      // verify the required parameter 'inlineObject' is set
      if (inlineObject === undefined || inlineObject === null) {
        throw new Error("Missing the required parameter 'inlineObject' when calling modifyOrganization");
      }

      var pathParams = {
        'organization_id': organizationId
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
        'Authorization': authorization,
        'X-Request-ID': opts['xRequestID'],
        'X-Giant-Swarm-Activity': opts['xGiantSwarmActivity'],
        'X-Giant-Swarm-CmdLine': opts['xGiantSwarmCmdLine']
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = V4Organization;
      return this.apiClient.callApi(
        '/v4/organizations/{organization_id}/', 'PATCH',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Modify organization
     * This operation allows you to modify an existing organization. You must be a member of the organization or an admin in order to use this endpoint.  The following attributes can be modified:  - `members`: By modifying the array of members, members can be added to or removed from the organization  The request body must conform with the [JSON Patch Merge (RFC 7386)](https://tools.ietf.org/html/rfc7386) standard. Requests have to be sent with the `Content-Type: application/merge-patch+json` header.  The full request must be valid before it will be executed, currently this means every member you attempt to add to the organization must actually exist in the system. If any member you attempt to add is invalid, the entire patch operation will fail, no members will be added or removed, and an error message will explain which members in your request are invalid. 
     * @param {String} authorization As described in the [authentication](#section/Authentication) section 
     * @param {String} organizationId An ID for the organization. This ID must be unique and match this regular expression: ^[a-z0-9_]{4,30}$ 
     * @param {module:model/InlineObject} inlineObject 
     * @param {Object} opts Optional parameters
     * @param {String} opts.xRequestID A randomly generated key that can be used to track a request throughout services of Giant Swarm. 
     * @param {String} opts.xGiantSwarmActivity Name of an activity to track, like \"list-clusters\". This allows to analyze several API requests sent in context and gives an idea on the purpose. 
     * @param {String} opts.xGiantSwarmCmdLine If activity has been issued by a CLI, this header can contain the command line 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/V4Organization}
     */
    this.modifyOrganization = function(authorization, organizationId, inlineObject, opts) {
      return this.modifyOrganizationWithHttpInfo(authorization, organizationId, inlineObject, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
