/**
 * The Giant Swarm API v4
 * This is the documentation for the Giant Swarm API starting at version `v4`.  For an introduction to Giant Swarm, refer to the [documentation site](https://docs.giantswarm.io/).  The Giant Swarm API attempts to behave in a __restful__ way. As a developer, you acess recources using the `GET` method and, for example, delete them using the same path and the `DELETE` method.  Accessing resources via GET usually returns all information available about a resource, while collections, like for example the list of all clusters you have access to, only contain a selected few attributes of each member item.  Some requests, like for example the request to create a new cluster, don't return the resource itself. Instead, the response delivers a standard message body, showing a `code` and a `message` part. The `message` contains information for you or a client's end user. The `code` attribute contains some string (example: `RESOURCE_CREATED`) that is supposed to give you details on the state of the operation, in addition to standard HTTP status codes. This message format is also used in the case of errors. We provide a [list of all response codes](https://github.com/giantswarm/api-spec/blob/master/details/RESPONSE_CODES.md) outside this documentation.  Feedback on the API as well as this documentation is welcome via `support@giantswarm.io` or on IRC channel [#giantswarm](irc://irc.freenode.org:6667/#giantswarm) on freenode.  ## Source  The source of this documentation is available on [GitHub](https://github.com/giantswarm/api-spec). 
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Body from './model/Body';
import V4AddClusterRequest from './model/V4AddClusterRequest';
import V4AddKeyPairRequest from './model/V4AddKeyPairRequest';
import V4AddKeyPairResponse from './model/V4AddKeyPairResponse';
import V4ClusterDetailsResponse from './model/V4ClusterDetailsResponse';
import V4ClusterListItem from './model/V4ClusterListItem';
import V4CreateUserRequest from './model/V4CreateUserRequest';
import V4GenericResponse from './model/V4GenericResponse';
import V4GetKeyPairsResponse from './model/V4GetKeyPairsResponse';
import V4GetKeyPairsResponseInner from './model/V4GetKeyPairsResponseInner';
import V4InfoResponse from './model/V4InfoResponse';
import V4InfoResponseGeneral from './model/V4InfoResponseGeneral';
import V4InfoResponseWorkers from './model/V4InfoResponseWorkers';
import V4InfoResponseWorkersCountPerCluster from './model/V4InfoResponseWorkersCountPerCluster';
import V4InfoResponseWorkersCpuCores from './model/V4InfoResponseWorkersCpuCores';
import V4InfoResponseWorkersInstanceType from './model/V4InfoResponseWorkersInstanceType';
import V4InfoResponseWorkersRamSizeGb from './model/V4InfoResponseWorkersRamSizeGb';
import V4InfoResponseWorkersStorageSizeGb from './model/V4InfoResponseWorkersStorageSizeGb';
import V4ModifyClusterRequest from './model/V4ModifyClusterRequest';
import V4NodeDefinition from './model/V4NodeDefinition';
import V4NodeDefinitionAws from './model/V4NodeDefinitionAws';
import V4NodeDefinitionCpu from './model/V4NodeDefinitionCpu';
import V4NodeDefinitionMemory from './model/V4NodeDefinitionMemory';
import V4NodeDefinitionStorage from './model/V4NodeDefinitionStorage';
import V4Organization from './model/V4Organization';
import V4OrganizationListItem from './model/V4OrganizationListItem';
import V4OrganizationMember from './model/V4OrganizationMember';
import V4ReleaseListItem from './model/V4ReleaseListItem';
import V4ReleaseListItemChangelog from './model/V4ReleaseListItemChangelog';
import V4ReleaseListItemComponents from './model/V4ReleaseListItemComponents';
import V4UserListItem from './model/V4UserListItem';
import ClustersApi from './api/ClustersApi';
import InfoApi from './api/InfoApi';
import KeyPairsApi from './api/KeyPairsApi';
import OrganizationsApi from './api/OrganizationsApi';
import ReleasesApi from './api/ReleasesApi';
import UsersApi from './api/UsersApi';


/**
* Generated JavaScript client for the Giant Swarm API v4..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var GiantSwarmV4 = require('index'); // See note below*.
* var xxxSvc = new GiantSwarmV4.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new GiantSwarmV4.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new GiantSwarmV4.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new GiantSwarmV4.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 4.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Body model constructor.
     * @property {module:model/Body}
     */
    Body,

    /**
     * The V4AddClusterRequest model constructor.
     * @property {module:model/V4AddClusterRequest}
     */
    V4AddClusterRequest,

    /**
     * The V4AddKeyPairRequest model constructor.
     * @property {module:model/V4AddKeyPairRequest}
     */
    V4AddKeyPairRequest,

    /**
     * The V4AddKeyPairResponse model constructor.
     * @property {module:model/V4AddKeyPairResponse}
     */
    V4AddKeyPairResponse,

    /**
     * The V4ClusterDetailsResponse model constructor.
     * @property {module:model/V4ClusterDetailsResponse}
     */
    V4ClusterDetailsResponse,

    /**
     * The V4ClusterListItem model constructor.
     * @property {module:model/V4ClusterListItem}
     */
    V4ClusterListItem,

    /**
     * The V4CreateUserRequest model constructor.
     * @property {module:model/V4CreateUserRequest}
     */
    V4CreateUserRequest,

    /**
     * The V4GenericResponse model constructor.
     * @property {module:model/V4GenericResponse}
     */
    V4GenericResponse,

    /**
     * The V4GetKeyPairsResponse model constructor.
     * @property {module:model/V4GetKeyPairsResponse}
     */
    V4GetKeyPairsResponse,

    /**
     * The V4GetKeyPairsResponseInner model constructor.
     * @property {module:model/V4GetKeyPairsResponseInner}
     */
    V4GetKeyPairsResponseInner,

    /**
     * The V4InfoResponse model constructor.
     * @property {module:model/V4InfoResponse}
     */
    V4InfoResponse,

    /**
     * The V4InfoResponseGeneral model constructor.
     * @property {module:model/V4InfoResponseGeneral}
     */
    V4InfoResponseGeneral,

    /**
     * The V4InfoResponseWorkers model constructor.
     * @property {module:model/V4InfoResponseWorkers}
     */
    V4InfoResponseWorkers,

    /**
     * The V4InfoResponseWorkersCountPerCluster model constructor.
     * @property {module:model/V4InfoResponseWorkersCountPerCluster}
     */
    V4InfoResponseWorkersCountPerCluster,

    /**
     * The V4InfoResponseWorkersCpuCores model constructor.
     * @property {module:model/V4InfoResponseWorkersCpuCores}
     */
    V4InfoResponseWorkersCpuCores,

    /**
     * The V4InfoResponseWorkersInstanceType model constructor.
     * @property {module:model/V4InfoResponseWorkersInstanceType}
     */
    V4InfoResponseWorkersInstanceType,

    /**
     * The V4InfoResponseWorkersRamSizeGb model constructor.
     * @property {module:model/V4InfoResponseWorkersRamSizeGb}
     */
    V4InfoResponseWorkersRamSizeGb,

    /**
     * The V4InfoResponseWorkersStorageSizeGb model constructor.
     * @property {module:model/V4InfoResponseWorkersStorageSizeGb}
     */
    V4InfoResponseWorkersStorageSizeGb,

    /**
     * The V4ModifyClusterRequest model constructor.
     * @property {module:model/V4ModifyClusterRequest}
     */
    V4ModifyClusterRequest,

    /**
     * The V4NodeDefinition model constructor.
     * @property {module:model/V4NodeDefinition}
     */
    V4NodeDefinition,

    /**
     * The V4NodeDefinitionAws model constructor.
     * @property {module:model/V4NodeDefinitionAws}
     */
    V4NodeDefinitionAws,

    /**
     * The V4NodeDefinitionCpu model constructor.
     * @property {module:model/V4NodeDefinitionCpu}
     */
    V4NodeDefinitionCpu,

    /**
     * The V4NodeDefinitionMemory model constructor.
     * @property {module:model/V4NodeDefinitionMemory}
     */
    V4NodeDefinitionMemory,

    /**
     * The V4NodeDefinitionStorage model constructor.
     * @property {module:model/V4NodeDefinitionStorage}
     */
    V4NodeDefinitionStorage,

    /**
     * The V4Organization model constructor.
     * @property {module:model/V4Organization}
     */
    V4Organization,

    /**
     * The V4OrganizationListItem model constructor.
     * @property {module:model/V4OrganizationListItem}
     */
    V4OrganizationListItem,

    /**
     * The V4OrganizationMember model constructor.
     * @property {module:model/V4OrganizationMember}
     */
    V4OrganizationMember,

    /**
     * The V4ReleaseListItem model constructor.
     * @property {module:model/V4ReleaseListItem}
     */
    V4ReleaseListItem,

    /**
     * The V4ReleaseListItemChangelog model constructor.
     * @property {module:model/V4ReleaseListItemChangelog}
     */
    V4ReleaseListItemChangelog,

    /**
     * The V4ReleaseListItemComponents model constructor.
     * @property {module:model/V4ReleaseListItemComponents}
     */
    V4ReleaseListItemComponents,

    /**
     * The V4UserListItem model constructor.
     * @property {module:model/V4UserListItem}
     */
    V4UserListItem,

    /**
    * The ClustersApi service constructor.
    * @property {module:api/ClustersApi}
    */
    ClustersApi,

    /**
    * The InfoApi service constructor.
    * @property {module:api/InfoApi}
    */
    InfoApi,

    /**
    * The KeyPairsApi service constructor.
    * @property {module:api/KeyPairsApi}
    */
    KeyPairsApi,

    /**
    * The OrganizationsApi service constructor.
    * @property {module:api/OrganizationsApi}
    */
    OrganizationsApi,

    /**
    * The ReleasesApi service constructor.
    * @property {module:api/ReleasesApi}
    */
    ReleasesApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
